server:
  port: 8000
spring:
  application:
    name: eureka-client-8000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/      # 属性对应服务注册中心的配置内容，指定服务注册中心的位置
