server:
  port: 9006
spring:
  application:
    name: eruka-consumer-feign-hystrix-9006

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/      # 属性对应服务注册中心的配置内容，指定服务注册中心的位置

# 启动微服务的hystrix监控功能
management:
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'hystrix.stream']
#        include: '*'   # *标识启动全部功能
